### ISSUE TITLE
no raknet-server and raknet-client artifacts in repo

### ISSUE THREAD

**Issue by nikolayKeniston** [yesdog/netty-raknet#8]
![image](https://github.com/yesdog/netty-raknet/assets/139270836/f7bfa3ca-5e96-4b7e-aeb4-f2586c6afd7b)

**Comment by colinrgodsey** [comment]
sorry for the delay. we need to find a new maven host still. for now, you should be able to just bundle the jars locally

**Comment by colinrgodsey** [comment]
@nikolay-keenetic new version released on a new maven host! details in the README
